// Copies extension/page-runtime.js into hooks/page-script.ts so both transports
// run the same page code. Run after editing the runtime.
const js = await Bun.file(new URL('../extension/page-runtime.js', import.meta.url)).text()
if (js.includes('`')) throw new Error('page-runtime.js must not contain backticks')
const out = `// GENERATED by scripts/sync-runtime.ts from extension/page-runtime.js. Do not edit.
export const PAGE_RUNTIME = String.raw\`
${js}\`
`
await Bun.write(new URL('../hooks/page-script.ts', import.meta.url), out)
const hook = await Bun.file(new URL('../extension/console-hook.js', import.meta.url)).text()
await Bun.write(new URL('../extension/hook-src.js', import.meta.url), `// GENERATED by scripts/sync-runtime.ts from console-hook.js. Do not edit.\nwindow.__CLAUDE_HOOK_SRC = ${JSON.stringify(hook)};\n`)
console.log('synced', js.length, 'bytes; hook', hook.length, 'bytes')
