// Copies extension/page-runtime.js into hooks/page-script.ts so both transports
// run the same page code. Run after editing the runtime.
const js = await Bun.file(new URL('../extension/page-runtime.js', import.meta.url)).text()
if (js.includes('`')) throw new Error('page-runtime.js must not contain backticks')
const out = `// GENERATED by scripts/sync-runtime.ts from extension/page-runtime.js. Do not edit.
export const PAGE_RUNTIME = String.raw\`
${js}\`
`
await Bun.write(new URL('../hooks/page-script.ts', import.meta.url), out)
console.log('synced', js.length, 'bytes')
